# Generated by Django 3.2.4 on 2021-06-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpostadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostAdmin',
        ),
    ]
